### ISSUE TITLE
Wrong line number after a GLSL shader error

### ISSUE THREAD

**Issue by ifernandez** [Spontz/Phoenix#11]
Take a look to this error log pertaining to a shader in error:

ERROR::Error [15:39:08 t: 62.6377] Shader Compile (Fragment - ./data/pool/shaders/planet/planet.glsl) log: 0(198) : error C0000: syntax error, unexpected "+=", expecting ',' or ';' at token "+="

ERROR::Error [15:39:08 t: 62.6377] Could not load shader: ./data/pool/shaders/planet/planet.glsl
ERROR::Error [15:39:08 t: 62.6377]   Section 54 [id: 90, DataSource: File: Netowrk] not loaded properly!

The 0(198) bit should point to the erroneous line in the .glsl file but it doesn't. The error is not there. I think that after joining the vertex and fragments shaders in one the error description messed up.

**Comment by perefm** [comment]
This cannot be done, because the error message comes directly from the OpenGL shader compiler, and the line number is almost impossible to parse. That's why its indicated the type of shader with the error (vertex/geometry/fragment).
Why dont we restant the line numbers in the shader editor when the keyword "@type" is found?

**Comment by ifernandez** [comment]
Without this feature, debugging a long shader becomes impossible. As it is now, you could replace the entire message by "There is an error in the shader".

I counted the lines, did substractions, nothing did work. I just need the exact line number with the problem.

**Comment by perefm** [comment]
fixed here: https://github.com/Spontz/Phoenix/commit/1ef91ae4be9ced50d8feddab7477fd1945e51b99
